---
# Elasticsearch Ansible Playbook
- hosts: all
  user: $user
  sudo: yes

  vars_files:
    - defaults/main.yml
    - vars/vagrant.yml

  tasks:
    - include_tasks: tasks/main.yml
    # Uncomment to install and enable SPM. Make sure to set the spm_client_token variable in your inventory.ini to your SPM key
    # - include_tasks: tasks/spm.yml

  handlers:
    - include_tasks: handlers/main.yml
