---
- name: "Install zip package"
  become: "yes"
  package:
    name: "zip"
    state: "present"

- name: "Check if JMSAppender.class has been removed"
  become: "yes"
  shell:
    cmd: "unzip -l log4j-*.jar | grep JMSAppender.class"
    chdir: "/usr/share/elasticsearch/lib"
  register: "__jmsappender_class"
  failed_when: "__jmsappender_class.rc not in [ 0, 1 ]"

- name: "Remove JMSAppender.class"
  become: "yes"
  shell:
    cmd: "zip -q -d log4j-*.jar org/apache/log4j/net/JMSAppender.class"
    chdir: "/usr/share/elasticsearch/lib"
  when:
    - "__jmsappender_class.rc == 0"
  notify: "Restart Elasticsearch"
