---
# Install Elasticsearch Plugins
#
# You will need to define an array called 'elasticsearch_plugins' in your playbook or inventory, such that:
#
# elasticsearch_plugins:
#  - name: '<plugin name>'
#  - url: '<plugin url>'
#  - ...
#
# where if you were to install the plugin via bin/elasticsearch-plugin, you would type:
#
# bin/elasticsearch-plugin install -b <plugin name or plugin url>

# Example for ingest-attachment (bin/elasticsearch-plugin install -b ingest-attachment)
# elasticsearch_plugins:
#  - name: 'ingest-attachment'
#
# Example https://github.com/infinilabs/analysis-pinyin (bin/elasticsearch-plugin install -b https://github.com/infinilabs/analysis-pinyin/releases/download/v6.8.23/elasticsearch-analysis-pinyin-6.8.23.zip)
# elasticsearch_plugins:
#  - url: "https://github.com/infinilabs/analysis-pinyin/releases/download/v6.8.21/elasticsearch-analysis-pinyin-6.8.21.zip"

# NOTE: all plugins are installed in batch mode, security permissions confirmed automatically

# Loop though elasticsearch_plugins and install them

- name: Installing Plugins by Name
  ansible.builtin.shell: 
    cmd: bin/elasticsearch-plugin install -b "{{ item.name }}"
    chdir: "{{ elasticsearch_home_dir }}"
  when: item.url is not defined
  with_items: "{{ elasticsearch_plugins }}"
  ignore_errors: yes

- name: Installing Plugins by URL
  ansible.builtin.shell:
    cmd: bin/elasticsearch-plugin install -b "{{ item.url }}"
    chdir: "{{ elasticsearch_home_dir }}"
  when: item.url is defined
  with_items: "{{ elasticsearch_plugins }}"
  ignore_errors: yes

# Fix permissions
- name: Fix Plugin Directory Permissions 
  ansible.builtin.file:
    path: "{{ elasticsearch_plugin_dir }}"
    state: directory
    owner: "{{ elasticsearch_user }}"
    group: "{{ elasticsearch_group }}"
    recurse: yes
